
augmentation: windowslice  # Default augmentation method

resampling:
  _target_: timeseries_augmentations.aug.resampling.Resampling
  upsampling_factor: 2.0
  subsequence_length_ratio: 0.25
#-------------------------------------------------------------------------------------------------------


augmentations:
  windowslice_S1: 
      view1:
        transforms:
          windowslice:
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.4
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03

            
      view2:
        transforms:
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.1  

#-------------------------------------------------------------------------------------------------------

  windowslice_S2: 
      view1:
        transforms:
          windowslice:
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.38
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03

            
      view2:
        transforms:
          windowslice:
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.4
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03

#-------------------------------------------------------------------------------------------------------


  maskedtimeseries_v1:
    view1:
      transforms:
        maskedtimeseries:
          _target_: timeseries_augmentations.aug.maskedtimeseries.MaskedTimeSeries
          mask_ratio: 0.1 # Mask % of the time series data
        jittering:
          _target_: timeseries_augmentations.aug.jittering.Jittering
          sigma: 0.03
    view2:
      transforms:
        maskedtimeseries:
          _target_: timeseries_augmentations.aug.maskedtimeseries.MaskedTimeSeries
          mask_ratio: 0.1 # Mask % of the time series data
        jittering:
          _target_: timeseries_augmentations.aug.jittering.Jittering
          sigma: 0.03 


#-------------------------------------------------------------------------------------------------------

  stiefelgen_v1: 
      view1:
        transforms:
          stiefelgen :
            _target_: timeseries_augmentations.aug.stiefelgen.StiefelGen
            window_size: 5
            beta: 0.001
            smoothing: True
          # jittering:
          #   _target_: timeseries_augmentations.aug.jittering.Jittering
          #   sigma: 0.03
            
      view2:
        transforms:
          stiefelgen :
            _target_: timeseries_augmentations.aug.stiefelgen.StiefelGen
            window_size: 15
            beta: 0.01
            smoothing: True
          # jittering:
          #   _target_: timeseries_augmentations.aug.jittering.Jittering
          #   sigma: 0.1



#-------------------------------------------------------------------------------------------------------



  stiefelgen1_v1: 
      view1:
        transforms:
          stiefelgen1 :
            _target_: timeseries_augmentations.aug.stiefelgen1.StiefelGen
            apply_to: bands
            beta: 0.01
          # jittering:
          #   _target_: timeseries_augmentations.aug.jittering.Jittering
          #   sigma: 0.03
            
      view2:
        transforms:
          stiefelgen1 :
            _target_: timeseries_augmentations.aug.stiefelgen1.StiefelGen
            apply_to: time
            beta: 0.01
          # jittering:
          #   _target_: timeseries_augmentations.aug.jittering.Jittering
          #   sigma: 0.03
#-------------------------------------------------------------------------------------------------------


  stiefelgen2_S1: 
      view1:
        transforms:
          stiefelgen2 :
            _target_: timeseries_augmentations.aug.stiefelgen2.StiefelGen
            beta: 0.05
            smooth: 5
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          # stiefelgen2 :
          #   _target_: timeseries_augmentations.aug.stiefelgen2.StiefelGen
          #   beta: 0.05
          #   smooth: 2
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
#-------------------------------------------------------------------------------------------------------
  stiefelgen2_S3: 
      view1:
        transforms:
          stiefelgen2 :
            _target_: timeseries_augmentations.aug.stiefelgen2.StiefelGen
            beta: 0.35
            smooth: 5
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          temporaldropout : 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.7
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
#-------------------------------------------------------------------------------------------------------



  magnitudewarping_v1: 
      view1:
        transforms:
          magnitudewarping: 
            _target_: timeseries_augmentations.aug.magnitudewarping.MagnitudeWarping
            sigma: 0.05
            knot: 4
          # jittering:
          #   _target_: timeseries_augmentations.aug.jittering.Jittering
          #   sigma: 0.1
            
      view2:
        transforms:
          # magnitudewarping: 
          #   _target_: timeseries_augmentations.aug.magnitudewarping.MagnitudeWarping
          #   sigma: 0.1
          #   knot: 15 
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.1
#-------------------------------------------------------------------------------------------------------

  temporaldropout_S1: 
      view1:
        transforms:
          temporaldropout : 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.9
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          # temporaldropout : 
          #   _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
          #   drop_rate: 0.7
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.1

#-------------------------------------------------------------------------------------------------------

  temporaldropout_S2: 
      view1:
        transforms:
          temporaldropout : 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.95
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          temporaldropout : 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.9
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
#-------------------------------------------------------------------------------------------------------
  temporaldropout_S3: 
      view1:
        transforms:
          temporaldropout : 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.7
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          windowslice:
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.4
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03

#-------------------------------------------------------------------------------------------------------
  cutmix_S1: 
      view1:
        transforms:
          cutmix: 
            _target_: timeseries_augmentations.aug.cutmix.CutMix
            alpha: 10 
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          # cutmix: 
          #   _target_: timeseries_augmentations.aug.cutmix.CutMix
          #   alpha: 0.7 
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.1





#-------------------------------------------------------------------------------------------------------
  interextrapolation_S1: 
      view1:
        transforms:
          interextrapolation:
            _target_: timeseries_augmentations.aug.interextrapolation.InterExtrapolation
            alpha: 6
            mode: interpolation
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          interextrapolation:
            _target_: timeseries_augmentations.aug.interextrapolation.InterExtrapolation
            alpha: 6 
            mode: both
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
#-------------------------------------------------------------------------------------------------------

  whitenoisewindow_S1: 
      view1:
        transforms:
          whitenoisewindow:
            _target_: timeseries_augmentations.aug.whitenoisewindow.WhiteNoiseWindow
            window_ratio: 0.2
            noise_std: 50
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
            
      view2:
        transforms:
          whitenoisewindow:
            _target_: timeseries_augmentations.aug.whitenoisewindow.WhiteNoiseWindow
            window_ratio: 0.2
            noise_std: 50
          jittering:
            _target_: timeseries_augmentations.aug.jittering.Jittering
            sigma: 0.03
#-------------------------------------------------------------------------------------------------------

  masked_temporal: 
      view1:
        transforms:
          maskedtimeseries:
            _target_: timeseries_augmentations.aug.maskedtimeseries.MaskedTimeSeries
            mask_ratio: 0.9 # Mask % of the time series data
          temporaldropout:
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.9

      view2:
        transforms:
          maskedtimeseries:
            _target_: timeseries_augmentations.aug.maskedtimeseries.MaskedTimeSeries
            mask_ratio: 0.9 # Mask % of the time series data
          temporaldropout:
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.9
#-----------------------------------------------------------------------------------

  temporal_window:
      view1: 
        transforms: 
          temporaldroupout: 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.7
          WindowSlice: 
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.4
      view2: 
        transforms: 
          temporaldroupout: 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.7
          WindowSlice: 
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.4

#-----------------------------------------------------------------------------------

  stiefelgen_temporal:
      view1: 
        transforms: 
          stiefelgen2 :
            _target_: timeseries_augmentations.aug.stiefelgen2.StiefelGen
            beta: 0.15
            smooth: 5
          temporaldroupout: 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.7


      view2: 
        transforms: 
          stiefelgen2 :
            _target_: timeseries_augmentations.aug.stiefelgen2.StiefelGen
            beta: 0.15
            smooth: 5
          temporaldroupout: 
            _target_: timeseries_augmentations.aug.temporaldropout.TemporalDropout
            drop_rate: 0.7
#-----------------------------------------------------------------------------------

  stiefelgen_window:
      view1: 
        transforms: 
          stiefelgen2 :
            _target_: timeseries_augmentations.aug.stiefelgen2.StiefelGen
            beta: 0.15
            smooth: 5
          WindowSlice: 
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.4


      view2: 
        transforms: 
          stiefelgen2 :
            _target_: timeseries_augmentations.aug.stiefelgen2.StiefelGen
            beta: 0.15
            smooth: 5
          WindowSlice: 
            _target_: timeseries_augmentations.aug.windowslice.WindowSlice
            reduce_ratio: 0.4

#-----------------------------------------------------------------------------------


seed : 42
selected_classes: [0, 2, 4, 7, 9]  # <- Liste fixe des classes à utiliser

selected_sample_index: 0  # toujours le premier échantillon de chaque classe
